#!/bin/bash

Delay=3

while [[ $REPLY != 0 ]]; do
    cat <<- EOF
    Please Select:
  1. Display System Information
  2. Display Disk Space
  3. Display Home Space Utilization
  0. Quit
EOF
    read -ep "Enter a number -> " 

    if [[ "$REPLY" =~ ^[0-3]$ ]]; then  
    if [[ "$REPLY" == 1 ]]; then
      echo "Hostname: $HOSTNAME"
      uptime
      sleep "$Delay"  
    fi

    if [[ "$REPLY" == 2 ]]; then
      df -h 
      sleep "$Delay"
    fi

    if [[ "$REPLY" == 3 ]]; then
      if (( "$(id -u)" == 0 )); then  
        echo "Home Space Utilization (All Users)"
        du -sh /home/*
      else  
        echo "Home Space Utilization ($USER)"
        du -sh "$HOME"
      fi
      sleep "$Delay"
    fi

  else
    echo "Invalid entry."  
    sleep "$Delay"
  fi
done

echo "Program terminated."