#!/bin/bash
# async-parent: Asynchronous execution demo (parent)

echo "Parent: starting..."
echo "Parent: launching child script..."

# Launch child script in the background
bash child &
pid=$!

echo "Parent: child (PID= $pid) launched."
echo "Parent: continuing..."
sleep 5

echo "Parent: pausing to wait for child to finish..."
wait "$pid"
echo "Parent: child is finished. Continuing..."
echo "Parent: parent is done. Exiting."
