#!/bin/bash
# pro-sub: demo of process substitution

# A while loop that processes the output of the `ls -l` command
while read attr links owner group size date time filename; do
cat <<- EOF
    Filename: $filename
    Size: $size
    Owner: $owner
    Group: $group
    Modified: $date $time
    Links: $links
    Attributes: $attr
EOF
done <<< "$(ls -l | tail -n +2)"

echo -e "\nSecond Method:\n"

while read attr links owner group size date time filename; do
cat <<- EOF
    Filename: $filename
    Size: $size
    Owner: $owner
    Group: $group
    Modified: $date $time
    Links: $links
    Attributes: $attr
EOF
done < <(ls -l | tail -n +2)

